# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NoteHistory",
        ),
    ]
