# Generated by Django 6.0.3 on 2026-03-14 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, help_text='Estimated cost in USD for this transcription session', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes_transcription_usage',
                'ordering': ['-created_at'],
            },
        ),
    ]
